### ISSUE TITLE
[Meta] Bug fixes targeting 7.5.0

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#106]
The goal here is to maintain a list of the remaining bugs we are planning to fix for the 7.5 release.

- [ ] https://github.com/elastic/kibana/issues/49391
- [ ] https://github.com/elastic/kibana/issues/49263
- [ ] https://github.com/elastic/kibana/issues/49246
- [ ] https://github.com/elastic/kibana/issues/49243
- [ ] https://github.com/elastic/kibana/issues/48576
