### ISSUE TITLE
Meta - Unify uptime documentation

### ISSUE THREAD

**Issue by dov0211** [elastic/uptime#20]
I had mapped out the changes we need to conduct on our documentation regarding Uptime (and Heartbeat)

Several sections on Uptime needs to be added across our documentation https://github.com/elastic/uptime/issues/7:
- [x] Create an uptime section in the [Product](https://www.elastic.co/guide/index.html) documentation 
- [x] Create a section in [Kibana](https://www.elastic.co/guide/en/kibana/current/index.html) user guide  https://github.com/elastic/kibana/pull/31814
- [x] Move Uptime app docs out of Kibana https://github.com/elastic/kibana/pull/67508
- [ ] Create a section on Uptime in [Heartbeat](https://www.elastic.co/guide/en/beats/heartbeat/current/index.html) 

Several updates on Heartbeat documentation:
- [x] Update Kubernetes autodiscovery in Heartbeat https://github.com/elastic/kibana/issues/34684 (minor update on Heartbeat)
~- [ ] Remove Heartbeat dashboard from the current documentation https://github.com/elastic/uptime/issues/16~ Closed
~- [ ] Heartbeat docs need more detail about loading dashboards https://github.com/elastic/beats/issues/11748~ Closed

cc: @bmorelli25

**Comment by bmorelli25** [comment]
FYI: We're having a discussion about Observability documentation over in https://github.com/elastic/observability-dev/issues/14. The first bullet point on this list might change depending on the outcome of that conversation. Feel free to weigh in.

**Comment by bmorelli25** [comment]
We've got the 👍for a new Uptime documentation book. Let me know when you're ready and I can make the changes in the docs repo.

**Comment by bmorelli25** [comment]
I've updated the issue description as it looks like most tasks have been accomplished. The only remaining task is to create a section on Uptime in Heartbeat.

cc @EamonnTP

**Comment by bmorelli25** [comment]
With the docs redesign happening soon, we won't be targeting the last remaining bullet point in this issue.
