### ISSUE TITLE
GUI Synthetics Recorder (tech preview)

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#304]
The script recorder will be worked on and implemented incrementally, falling into the following phases:

### Prerequisites

- [x] Validate if chromium can be bundled as part of the Electron application
- [x] Spike with Playwright and Synthetics 

### Phase 1

Goal: Enable users to write / edit tests without knowing javascript.

- [x] Can perform full range of CRUD operations on recorded steps (This includes
changing selector names, updating description for steps, etc) without knowing/using javascript.
- [ ] Ability to Start and Stop the recorder at arbitrary steps 
    - Open a new recorder session if there is no active session and execute
  the selected step
    - Execute only the current step when there is an active recorder session 
- [x] Allows users to export the script (Synthetics Journey/Steps format) which
can be copied and pasted in `heartbeat.yml` file or can be copied as suites
files, or pasted into the Fleet Integration configuration (https://github.com/elastic/uptime/issues/276).
- [ ] Support workspace UI (subject to user journeys @drewpost working on these)
    - Left hand panel with list of journeys
    - Right hand panel for editing steps in selected journey
    - Use the Intermediate representation (IR) and export whole workspace as JSON
    - Save the IR in the local file system
    - Add ability in UI to load/import from the saved IR
- [x] Build the recorder in React and use EUI component library so we can
code share with Kibana at some point. 
- [ ] Integration with Fleet would preferably use Fleet API, but if not, users can use script export to copy/paste into Fleet UI.
- [ ] Released as technical preview (aka experimental)

### Phase 2

- [x] Add support for assertions  
    - Ability to add assert commands if element is present on the page (query
      by id, classname, etc.)
- [ ] Allow support for consuming the IR format in the synthetics agent like how
one could specify the suite file.
- [ ] IR would be the single point of truth which would be used across Kibana,
Synthetics and Recorder app.
- [ ] Add integration with the Kibana fleet UI which could piggy back to the
installed recorder. 
   - Kibana would pull the IR from the recorder and pass it to heartbeat agent
   which would be sent to synthetics to perform the run. 
- [ ] Library of saved snippets etc. that can be shared between recordings. Things like 'log in', etc. that people don't want to repeatedly record. Saved objects in Uptime app would back this.
 

### Later:
- [ ] Investigate change history feature (ability to rewind config changes, look at who changed what in fleet). Will require integration with fleet team.

**Comment by vigneshshanmugam** [comment]
Two options we can do for bundling the chromium

1. use the browser fetcher to start downloading chromium before the electron process kicks and we show the recorder UI

2. We bundle it along with recorder app and modify the synthetic driver runner to launch the executable from installed path via `executablePath` launch option. 

Reference - https://playwright.dev/docs/installation/

**Comment by andrewvc** [comment]
@vigneshshanmugam I think bundling it makes sense for now, and will work better in air-gapped envs

**Comment by vigneshshanmugam** [comment]
Good point @andrewvc, Yes lets go with option 2 and bundle it along with the recorder app.

**Comment by paulb-elastic** [comment]
We should consider if the “export as a script” is a better thing to implement initially, over “make Synthetics understand IR” as this means we can also use the recorder in advanced cases where additional script code needs adding (e.g. for some dynamic logic). If we only have a “save IR” option and paste that into the Heartbeat/Synth script, we don’t have the opportunity for additional script code at all.

**Comment by vigneshshanmugam** [comment]
Moved the list to the main description

**Comment by paulb-elastic** [comment]
Closing and this is done to the extent it needs to be for the 7.16 release, and will continually be updated via other issues (the script recorder is not part of the stack release).
