### ISSUE TITLE
[Meta] Heartbeat and Elastic Integration

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#309]
Meta issue to track the various deliverables of the integration between Heartbeat and the Elastic Agent:
- [ ] Elastic Agent and Heartbeat Integration - Phase 1
  - HTTP/ICMP/TCP Ping available as an integration in Fleet (i.e. not separately accessible via Uptime) https://github.com/elastic/uptime/issues/235
  - Includes being based on a custom UI https://github.com/elastic/kibana/issues/91062
  - Requires support for data streams https://github.com/elastic/kibana/issues/91031
- [ ] Elastic Agent and Heartbeat Integration - Phase 2
  - Real Browser Synthetic Agent as an integration in Fleet (i.e. not separately accessible via Uptime) https://github.com/elastic/uptime/issues/276

Additional requirements to improve UX and onboarding (which could be done after or in between the above phases, depending on priorities:

- [ ] Quick access to edit Fleet/Integration monitor from Uptime
  - Simple way for users to get from the Uptime UI, to the configuration (in Fleet) for the monitor
  - https://github.com/elastic/uptime/issues/307
- [ ] Add data flow
  - The *Add Data* workflow in Uptime (that directs users to download/install/run Heartbeat), needs changing to be implemented via Agent/Fleet
  - https://github.com/elastic/uptime/issues/310 (this is not yet fully defined and needs specifying)
- [ ] Onboarding and managing monitors from Uptime UI
  - Although underpinned through a Fleet/Integration implementation, this is for users to be able to stay within the Uptime UI and fully manage those monitors, without needing to *understand* Fleet
  - https://github.com/elastic/uptime/issues/308 (this is not yet defined and needs specifying, and will also require help from the Design team)
  - Refer to https://docs.google.com/document/d/1w2ZZq53cN5aDVeln_0XGWv2FVb0SUOBXY1Yn51RuJ5w/edit#heading=h.uvo1cbzesuqb
