### ISSUE TITLE
[Meta] Uptime server enhancements for synthetics service

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#400]
[WIP] This is still a work in progress, i will add few more items in the list

This issue is to track all the requirement/enhancements we need in Kibana uptime server code to interact with synthetics service and respective UI code in the uptime app.

### Feature Flag
- [x] https://github.com/elastic/uptime/issues/421 Add a feature flag that will be used via config file to enable all the synthetics service functionality on server side and ui

### Data model: 
- [x] https://github.com/elastic/uptime/issues/396
we will have to define data model to save uptime monitor configuration, we will leverage kibana saved objects apis to do that.
Example monitor attributes are
id, Name, type, urls etc all the data that user will define while creating a monitor will need to be saved in a saved object , detailed options can be found here 
https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html
- [x] https://github.com/elastic/kibana/pull/120105
- [x] https://github.com/elastic/uptime/issues/420

### Task manager
- [x] https://github.com/elastic/uptime/issues/397
We will need to define a scheduled task using Kibana task manager, which will run periodically to push monitor configurations to the synthetics service
- [x] https://github.com/elastic/kibana/issues/121233
### API Key Generation
- [x] https://github.com/elastic/uptime/issues/398
We need to pass an API key generated by kibana to the synthetic service, that will be used by heartbeat to communicate with elasticsearch. 
- [x] https://github.com/elastic/kibana/pull/119990
- [x] https://github.com/elastic/uptime/issues/419

### ES Hosts determination
- [x] https://github.com/elastic/uptime/issues/399
We will need to write a helper function to determine es hosts, so that those can be fetched and pass to the synthetics service.

### Generate index templates
- [x] https://github.com/elastic/uptime/issues/405
Using fleet api  we need to install synthetics integration package to install proper data stream index templates required to query uptime data

### Mtls communication with service

- [x] https://github.com/elastic/uptime/issues/436

### Add a route to get service locations

- [x] Using manifest file config, we need to add a route to get available service locations

## Service Interface
- [x] https://github.com/elastic/uptime/issues/422
- [x] https://github.com/elastic/uptime/issues/424
- [x] https://github.com/elastic/kibana/pull/119843
- [x] https://github.com/elastic/uptime/issues/423

## Monitor CRUD Routes
We will need following routes in the server side to meet UI requirements

- [x] Create monitor and push it to service https://github.com/elastic/uptime/issues/401
- [x] Edit monitor and update the service https://github.com/elastic/uptime/issues/402
- [x] Delete monitor and ask service to delete it as well https://github.com/elastic/uptime/issues/403
- [x] Add data validation to routes https://github.com/elastic/uptime/issues/410

**Comment by shahzad31** [comment]
Closing this as pieces needed for tech preview are already done !!
