### ISSUE TITLE
[Meta] Uptime public UI enhancements for Synthetics service

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/uptime#407]
This issue is to track all the requirement/enhancements we need in Kibana uptime public code to interact with synthetics service and respective server code in the uptime app.

### Feature flag implementation
- [x] elastic/uptime#408
This could be a new feature flag, for example, `xpack.uptime.unsafe.service.enabled` or an existing service-only key that we will set directly for our private beta customers `xpack.uptime.unsafe.service.url`.

### Add / Edit Monitors: 
- [x] elastic/uptime#409
Add a new page to create and save a heartbeat monitor. Existing components and state management from the Elastic Synthetics Integration should be reused where possible. Saving a monitor should save the configuration to saved objects. 
- [x] elastic/uptime#412
Add a new page to edit a monitor based on id will need to define a scheduled task using Kibana task manager, which will run periodically to push monitor configurations to the synthetics service
- [x] elastic/uptime#416
- [x] elastic/uptime#428
- [x] elastic/uptime#427

### Creation flow, save redirect
- [x] Redirect the user to the appropriate place after saving a monitor (Closed with https://github.com/elastic/kibana/pull/120038)

### Management page, "new" monitors
- [x] elastic/uptime#413
We need to pass an API key generated by kibana to the synthetic service, that will be used by heartbeat to communicate with elasticsearch. 

### Validation
- [x] https://github.com/elastic/kibana/issues/120798

### Monitor Management Table
- [x] https://github.com/elastic/uptime/issues/415
- [x] https://github.com/elastic/kibana/issues/121006

### One shot mode
- [x] Implement one shot mode to test monitor configuration](https://github.com/elastic/uptime/issues/437

### Run Now/Trigger now mode
- [x] https://github.com/elastic/uptime/issues/440

### Creation flow dependencies
- [x] Ensure Elastic Synthetics package and index templates are created is installed before loading the add monitor
Before a monitor can successfully be created, we must ensure the mappings are created and the API key exists

Resolved by https://github.com/elastic/kibana/pull/119727 and Fleet auto upgrade flow

### Edit flow, ensure package spec is up to date
- [x] Ensure that the latest synthetics integration package is installed when editing a policy
Just like the creation flow, we must ensure that the latest version of the integration package is installed when editing a monitor.

Resolved by https://github.com/elastic/kibana/pull/119727 and Fleet auto upgrade flow

### Polish
- [x] Update formatting for Schedule in the UI Monitor Management table from `@every 3m` to a more readable format: https://github.com/elastic/kibana/issues/125739
- [x] Check cell alignment https://github.com/elastic/kibana/pull/121454#issuecomment-999032467
- [x] Limit cell widths https://github.com/elastic/kibana/pull/121454#pullrequestreview-837780604

### Enhancments
- [x] https://github.com/elastic/kibana/issues/121707
- [x] https://github.com/elastic/kibana/issues/121446

### Bugs
- [x] https://github.com/elastic/kibana/issues/120808
- [x] https://github.com/elastic/kibana/issues/121549
- [x] https://github.com/elastic/kibana/issues/121548
- [x] https://github.com/elastic/kibana/issues/121477
- [x] https://github.com/elastic/kibana/issues/121327
- [x] https://github.com/elastic/kibana/issues/121232

**Comment by paulb-elastic** [comment]
@dominiqueclarke I'm going to pop this onto the 8.0 board so it's easier to find

**Comment by paulb-elastic** [comment]
Last item (https://github.com/elastic/kibana/issues/125739) done, so closing
