### ISSUE TITLE
[Meta] Uptime UI Enhancements for Synthetics Service Beta

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/uptime#433]
### Management page, "legacy" monitors
- [ ] UI Monitor Management Monitors Table - "Legacy" Monitors

### Monitor management page, metrics
- [x] elastic/uptime#414

### Filters
- [x] https://github.com/elastic/kibana/issues/120785
- [x] https://github.com/elastic/kibana/issues/121126

### Search
- [ ] Add search bar to UI Monitor Management table

### Sorting
- [x] https://github.com/elastic/kibana/issues/121117

### Management page - interim state
- [ ] Display information about inprogress checks for immediate user feedback

**Comment by paulb-elastic** [comment]
More UI enhancements moved to 8.3 planning

**Comment by paulb-elastic** [comment]
Covered in https://github.com/elastic/kibana/issues/128300
