### ISSUE TITLE
[META] Reconcile spaces with monitor management and data views

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#463]
With the new monitor management feature we now have monitors defined using saved objects in kibana. This creates a situation where the data visible in the Uptime app is contingent on the space in-use. The app reads from two places:

1. Data streams
2. Kibana saved objects

It is currently up to the user to configure this which is confusing. If a user creates monitors in spaces A and B, they will see data from both spaces in the Uptime app (except the monitor management UI).

This issue proposes that we automatically set the namespace for monitors created in monitor management to the space name. It also proposes that we, by default, use that in the index pattern used in the Uptime app settings page.

If we agree this makes sense we'll need to figure out if we need to do some level of migration from our current strategy to this one for current users.

Related to https://github.com/elastic/kibana/issues/128192 , it opens a question of where data views fit in here. Data views assume that users want the opposite of this strong coupling. This issue proposes we deviate from the 'standard' way o11y works, which presumes that configuration of data generating things is separate from the viewing of them.

Tasks:
- [x] https://github.com/elastic/kibana/issues/128820
- [ ] Read synthetic monitors out of the current space only by default
- [ ] Determine how this will all work, if at all, with cross cluster search. I don't see how it can

**Comment by andrewvc** [comment]
CC @drewpost @liciavale thoughts on the UX here?

**Comment by andrewvc** [comment]
Closed due to a new approach of filtering based on saved objects
