### ISSUE TITLE
[Meta] Monitor Optimization and Enhancements (aka Project MOE)

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#65]
This is a meta issue to track improvements to both query performance and accuracy. For further background read [this google doc](https://docs.google.com/document/d/1VjnY5KB7GeeurNwutUzltZJICms-_Re67gQHTx8eQgg/edit). We've decided to use real-time queries only, with no background jobs. 

- [ ] Add new ordered group [beats#12920](https://github.com/elastic/beats/pull/12920)
- [ ] Load expandable monitor overview page drawers async to simplify background query for component.
- [ ] Add full list of IPs to heartbeat monitor summaries to optimize queries as well as min/max/average duration.

**Comment by andrewvc** [comment]
Closing this as  #63 involved making the queries so fast this is unnecessary.
