### ISSUE TITLE
[Meta] Uptime Redesign

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#79]
This meta issue tracks the implementation of the design overhaul of the Uptime app. Screenshots are provided at the bottom of this issue.

## Tasks
- [x] New overview page 
  - [x] New overview status panel ( https://github.com/elastic/kibana/issues/44533 )
  - [x] New MonitorList Expanded row ( https://github.com/elastic/kibana/issues/44541 )
    - [x] Add filters to expanded row https://github.com/elastic/kibana/pull/52609
- [x] New details page
  - [x] New details status panel + location world map ( https://github.com/elastic/kibana/issues/44550 )
  - [x] Use red-gray color scheme on pings histogram ( https://github.com/elastic/kibana/issues/44553 )
~~- [ ] Monitor timelines ( https://github.com/elastic/kibana/issues/44546 )~~

## Sequencing

We should tackle tasks in the following order:

1. Everything on the overview page, there are few dependencies here. The one exception is the timeline widget, which can be temporarily implemented via the current mini histogram used on monitor rows on the current overview page.
2. New details page: This has more complexity, and has the new map widget.
3. Monitor Timelines: Even though we have a working PoC it's a lot of code. We should add this in as a final evolutionary phase.

Overview Page

![image](https://user-images.githubusercontent.com/131427/64043132-2ec0dd80-cb29-11e9-90a8-f4eba3a43ff4.png)

Details Page

![image](https://user-images.githubusercontent.com/131427/64043462-1f8e5f80-cb2a-11e9-95aa-ceb948a614dd.png)

**Comment by justinkambic** [comment]
@andrewvc what is your thinking about the implementation process for these enhancements? Should we create separate components that we can host in `master`, and then perform a switch when all items are completed? Or we complete them piecemeal and have `master` straddle the enhanced design with the legacy styling?

**Comment by andrewvc** [comment]
@justinkambic we can go piecemeal here, the components are an improvement individually as well as combined.

**Comment by shahzad31** [comment]
Seems like we need to get to timelines at some point.
