### ISSUE TITLE
Uptime 7.5.0 release tracking

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#94]
This issue should track all backport PR's related to the `7.5.0` release, and any fix or test PR's we want to add to the release that have yet to be merged/backported.

## Features (due Oct 15)
- [x] https://github.com/elastic/kibana/pull/48037
- [x] https://github.com/elastic/kibana/pull/47952
- [x] https://github.com/elastic/kibana/pull/48120

## Tests / Fixes
- [x] https://github.com/elastic/kibana/pull/47766
- [ ] https://github.com/elastic/kibana/pull/47633
- [x] https://github.com/elastic/kibana/pull/47963

**Comment by andrewvc** [comment]
Closing as there is one item left that is already well tracked.
